name: Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with: { node-version: 22.15.0 }
      - run: npm install
      - run: mkdir -p public && cp -r $(ls -A | grep -v "public" | grep -v ".gitignore") public/
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: public
